### ISSUE TITLE
Feature Request: Quiz Generation Without User Selection

### ISSUE THREAD

**Issue by rahul1841** [CodeHarborHub/codeharborhub#101]
Description:  In the current quiz application, users are able to start a quiz without selecting any category, difficulty, type, or amount of questions. This can lead to a less tailored and potentially confusing quiz experience. Additionally, the user interface (UI) of the Quiz App section could be improved for better usability and visual appeal.
Use Case: To address this issue, I propose implementing a feature that requires users to select a category, difficulty, type, and amount of questions before they can start a quiz. Additionally, I will improve the UI of the Quiz App section to make it more intuitive and visually appealing.
Conclusion: By implementing this feature, we will ensure that users cannot start a quiz without making necessary selections, resulting in a more customized and satisfying quiz experience. Enhancing the UI will further improve usability, making the quiz app more attractive and easier to navigate. I am confident in my ability to implement these improvements and enhance the overall user experience of the quiz app.
@CodeHarborHub  please assign it to me .

**Comment by rahul1841** [comment]
Description: In the current quiz application, users are able to start a quiz without selecting any category, difficulty, type, or amount of questions. This can lead to a less tailored and potentially confusing quiz experience. Additionally, the user interface (UI) of the Quiz App section could be improved for better usability and visual appeal.
Use Case: To address this issue, I propose implementing a feature that requires users to select a category, difficulty, type, and amount of questions before they can start a quiz. Additionally, I will improve the UI of the Quiz App section to make it more intuitive and visually appealing.
Conclusion: By implementing this feature, we will ensure that users cannot start a quiz without making necessary selections, resulting in a more customized and satisfying quiz experience. Enhancing the UI will further improve usability, making the quiz app more attractive and easier to navigate. I am confident in my ability to implement these improvements and enhance the overall user experience of the quiz app.
https://github.com/CodeHarborHub please assign it to me .

**Comment by Ajay-Dhangar** [comment]
You can work on creating a new component for it because currently, the quiz is in another app and not integrated into our site.

**Comment by Ajay-Dhangar** [comment]
<img src="https://readme-typing-svg.demolab.com?font=Fira+Code&size=24&weight=900&pause=1000&color=0FF26C&random=false&center=false&width=1500&height=100&lines=Announcement:+Contributors,+please+ensure+tasks+are+completed+within+assigned+timeframes+as+per+project+sidebar." alt="Announcement" />

**Comment by Ajay-Dhangar** [comment]
> Can I work on this @Ajay-Dhangar i will create a new component for quiz as described above

Sorry, it is not currently available on our site. We are using a reference. Once our back-end development is complete, we will add our own setup, which will include more features such as user login and a dashboard.
