### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#106]

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i'd love to work on creating HTML list tutorials! can i be assigned to work on this?

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i just submitted a PR for this topic. could you please review and suggest changes?

**Comment by iamanolive** [comment]
could you also please mark this issue as completed @Ajay-Dhangar
