### ISSUE TITLE
Basic Syntax and Data Types of Java

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#114]
Covered three topics [code](https://github.com/CodeHarborHub/codeharborhub/tree/main/docs/java/basic-syntax-and-data-types) and [preview](https://www.codeharborhub.live/docs/category/basic-syntax-and-data-types-of-java). 

- [ ] Java Syntax and Structure
- [ ] Variables and Data Types
- [ ] Operators and Expressions

**Resources for Guidance**

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- https://www.codeharborhub.live/community/features
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Our Site Features**

https://www.codeharborhub.live/community/features

**Comment by Tirth-chokshi** [comment]
Hello @Ajay-Dhangar i can complete this ! please assign me this issue under GSSOC'24

**Comment by Shweta-281** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?

**Comment by Ajay-Dhangar** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?

okay
