### ISSUE TITLE
Add on DSA: Binary Trees

### ISSUE THREAD

**Issue by W-ight** [CodeHarborHub/codeharborhub#116]
* **Description:**  In the dsa section i would like to add binary tree topics under Intermediate topics
* **Use Case:** There is already a beginner section which include basic dsa topic. Now for Intermediate section we could start with Binary tree.

 I would like to start the work on  Binary tree topic @Ajay-Dhangar , under gssoc24.

**Comment by Ajay-Dhangar** [comment]
**Resources for Guidance**

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- https://www.codeharborhub.live/community/features
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA features on our site is supported**
- Tabs: [switch languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [line-numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)
