### ISSUE TITLE
Add on DSA: C++ STL

### ISSUE THREAD

**Issue by Suvam3456** [CodeHarborHub/codeharborhub#121]
. Description: In the dsa section i would like to add C++ STL under Intermediate topics.
. Use Case: There is already a beginner section which include basic dsa topic. Now for Intermediate section we could start with C++ STL like Map, Vector, set ,, multiset , lower_bound, upper_bound etc and also in-built fns in c++  which is very important to learn in competitive programming also to solve medium and hard DSA problems.

Just an example image of some STL topics from any random website :
![image](https://github.com/CodeHarborHub/codeharborhub/assets/99579881/1ab10684-d729-412f-b37c-a7f78cd8bb4c)

I would like to start the work on C++ STL @Ajay-Dhangar  , under GSSOC'24 and please add level label as well.

**Comment by Ajay-Dhangar** [comment]
**Resources for Guidance**

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- https://www.codeharborhub.live/community/features
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA features on our site is supported**
- Tabs: [switch languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [line-numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

**Comment by Chanc2206** [comment]
hey can you assign this to me i can work over this?

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i'd love to work on this!

**Comment by Ajay-Dhangar** [comment]
> hi @Ajay-Dhangar i'd love to work on this!

Alright, you can go ahead and try it since it has been pending for two weeks. I can assign it to you (@iamanolive).
