### ISSUE TITLE
Login and Sign up on Navabar with Login page as pop-up on the same page.

### ISSUE THREAD

**Issue by Suvam3456** [CodeHarborHub/codeharborhub#122]
I would like to add  Login and Sign up buttons on Navbar of your Website. The Login page will come with a small window pop-up on the same page on clicking it.

I can customise UI and navbar according to your demands . This is only the front-end work of Login and Signup.

An example from  a random website , when clicking on Login button , how it comes.

![image](https://github.com/CodeHarborHub/codeharborhub/assets/99579881/a50a50cb-e76c-4a53-908a-aae7a679dea4)

@Ajay-Dhangar If you want you can Assign me this under GSSOC'24 and please add label of level also so that I can get relevant points for my work.

**Comment by Ajay-Dhangar** [comment]
Hi @Suvam3456 

Thank you for suggesting the addition of Login and Sign up buttons to our website, https://www.codeharborhub.live/. I truly appreciate your interest in enhancing our frontend user experience.

Currently, our development efforts are primarily focused on the backend, ensuring that our platform can efficiently handle large data and accommodate various modules to provide a seamless experience for our users. Given the ongoing work on the backend, I believe it would be best to prioritize these tasks to ensure the stability and scalability of our platform.

While I understand the importance of frontend enhancements like adding Login and Sign up buttons, I believe it would be more efficient to address them once our backend work is completed. This approach will allow us to integrate these features seamlessly into our existing system, ensuring a cohesive user experience across the board.

Rest assured, your suggestion has been duly noted, and we will revisit it once we have completed the current phase of backend development. I truly appreciate your understanding and patience as we work towards making Code Harbor Hub the best platform it can be.

If you have any further suggestions or feedback, please feel free to share them with us. Your input is invaluable as we strive to improve our platform.

Thank you once again for your understanding.

Best regards,

Best regards,
@Ajay-Dhangar
