### ISSUE TITLE
2D Array is missing

### ISSUE THREAD

**Issue by Chanc2206** [CodeHarborHub/codeharborhub#127]
* **Description:** In a given array section, it is briefly explained about one-dimensional arrays, but we did not talk about two-dimensional arrays, which I believe is significant and should be included, and the sorting part should be included in another section called sorting techniques.
* **Use Case:** 1. Structure of 2D array
2. Indexing
3. Initialization
4.Accessing
5. Problem for practise
* **Similar Features:** (Optional) We would be different because here I'm going to all the problems from basic to advanced with the corporate tags.

**Comment by Ajay-Dhangar** [comment]
You can try it, and I'll be here to assist you along the way.

**Comment by Chanc2206** [comment]
ok sir

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i'd love to work on this!

**Comment by Ajay-Dhangar** [comment]
Okay, @iamanolive

**Comment by iamanolive** [comment]
@Ajay-Dhangar submitted PR/
