### ISSUE TITLE
Bug Report, GSSOC24: Typos in Contributing.md

### ISSUE THREAD

**Issue by KDHarsh24** [CodeHarborHub/codeharborhub#147]
Typos in Contributing.md

**Comment by Ajay-Dhangar** [comment]
can you explain

**Comment by Tirth-chokshi** [comment]
@Ajay-Dhangar In Contributing.md file name of repository is mentioned as ResourceHub Instead of CodeHarborHub in line number 42,43,60 and 68 can i correct it under GSSOC'24

**Comment by Ajay-Dhangar** [comment]
okay update now

**Comment by Tirth-chokshi** [comment]
can close this as complete - pull request #151
