### ISSUE TITLE
Feature Request: Adding hovering effect

### ISSUE THREAD

**Issue by reshamsai150** [CodeHarborHub/codeharborhub#150]
![image](https://github.com/CodeHarborHub/codeharborhub/assets/164533685/a8e82f7e-3a52-4501-bbc5-bda53a990c3c)
adding hover effect for these cards in this section

**Comment by Tirth-chokshi** [comment]
Hello @Ajay-Dhangar I want to work on this can you assign please me

**Comment by KDHarsh24** [comment]
I can do i with Sliding hover use

**Comment by Ajay-Dhangar** [comment]
> I can do it with Sliding animation of hover use

okay

**Comment by Ajay-Dhangar** [comment]
> Hello @Ajay-Dhangar I want to work on this can you assign please me

What work you like on home page. And how to you solve can you explain.

**Comment by Tirth-chokshi** [comment]
In home page Get Started and Courses buttons are enhanced with hover effects. My proposal is to extend this feature to the Course’ and Features cards By doing so, we can maintain a consistent UX and it will align with the theme of UI

![Screenshot 2024-05-19 093223](https://github.com/CodeHarborHub/codeharborhub/assets/122982506/1dcd395b-01ce-4f09-87cf-7523c7031862)

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar In home page Get Started and Courses buttons are enhanced with hover effects. My proposal is to extend this feature to the Course’ and Features cards By doing so, we can maintain a consistent UX and it will align with the theme of UI
> 
> ![Screenshot 2024-05-19 093223](https://private-user-images.githubusercontent.com/122982506/331846291-1dcd395b-01ce-4f09-87cf-7523c7031862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTIxODQsIm5iZiI6MTcxNjA5MTg4NCwicGF0aCI6Ii8xMjI5ODI1MDYvMzMxODQ2MjkxLTFkY2QzOTViLTAxY2UtNGYwOS04N2NmLTc1MjNjNzAzMTg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNDExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTdkNDJjMGM2MjgyZTYyNzI4ZDg1MWZmMTJmY2YxOWM0ZWU3ZjQ2MTllZTIzMjIzNDgzYmY5NzJjNWM4OGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0OLgkFEJDcAU__JFXcdfBHzQc_Q0JS1eHXEbjNjmaZ0)

Checkout: https://education-html.themerex.net/courses-streampage.html

![image](https://github.com/CodeHarborHub/codeharborhub/assets/99037494/c82b2e93-f7e3-4072-82d4-590c1559e0be)

**Comment by Ajay-Dhangar** [comment]
> > @Ajay-Dhangar In home page Get Started and Courses buttons are enhanced with hover effects. My proposal is to extend this feature to the Course’ and Features cards By doing so, we can maintain a consistent UX and it will align with the theme of UI
> > ![Screenshot 2024-05-19 093223](https://private-user-images.githubusercontent.com/122982506/331846291-1dcd395b-01ce-4f09-87cf-7523c7031862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTIxODQsIm5iZiI6MTcxNjA5MTg4NCwicGF0aCI6Ii8xMjI5ODI1MDYvMzMxODQ2MjkxLTFkY2QzOTViLTAxY2UtNGYwOS04N2NmLTc1MjNjNzAzMTg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNDExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTdkNDJjMGM2MjgyZTYyNzI4ZDg1MWZmMTJmY2YxOWM0ZWU3ZjQ2MTllZTIzMjIzNDgzYmY5NzJjNWM4OGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0OLgkFEJDcAU__JFXcdfBHzQc_Q0JS1eHXEbjNjmaZ0)
> 
> Checkout: https://education-html.themerex.net/courses-streampage.html
> 
> ![image](https://private-user-images.githubusercontent.com/99037494/331846764-c82b2e93-f7e3-4072-82d4-590c1559e0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTI1ODgsIm5iZiI6MTcxNjA5MjI4OCwicGF0aCI6Ii85OTAzNzQ5NC8zMzE4NDY3NjQtYzgyYjJlOTMtZjdlMy00MDcyLTgyZDQtNTkwYzE1NTllMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA0MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDBmMDE4NWMwZmJiNDNmYjQ5ZDBlM2JiNzVjY2VkM2IwYmM0YTFlNjJlODA5NGQwYzg5MTU2MzNhNTU1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejdPh1HNnqwGnKJDQC_WnBmltjEI_z__n6dLxHZttIA)

You try like this for good experience

**Comment by KDHarsh24** [comment]
Sure just give me some time.

**Comment by Ajay-Dhangar** [comment]
> Sure just give me some time.

Okay, work on it and you need any help then drop me message. I will help you.
