### ISSUE TITLE
Bug Report: `value' is missing in props validation

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#166]
### Where is the issue?

https://github.com/CodeHarborHub/codeharborhub/tree/main/courses/react-js/advanced-level/component-optimization/MemoizationExample.js

### Why is this an issue?

In JavaScript, props are typically passed as plain objects, which can lead to errors and confusion when working with components that have specific prop requirements. However, it lacks of type safety and clarity when passing props to components in a codebase.

By defining types for component props, developers can enforce type safety and provide clear documentation for the expected props of a component. This helps catch potential errors at compile-time. It also improves code maintainability by making it easier to understand how components should be used and what props they accept.

### How can I fix it?

**Noncompliant code example**

```js
import PropTypes from 'prop-types';

function Hello({ firstname, lastname }) {
  return <div>Hello {firstname} {lastname}</div>; // Noncompliant: 'lastname' type is missing
}
Hello.propTypes = {
  firstname: PropTypes.string.isRequired
};

// Using legacy APIs

class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.firstname} {this.props.lastname}</div>; // Noncompliant: 'lastname' type is missing
  }
}
Hello.propTypes = {
  firstname: PropTypes.string.isRequired,
};
Compliant solution
import PropTypes from 'prop-types';

function Hello({ firstname, lastname }) {
  return <div>Hello {firstname} {lastname}</div>;
}
Hello.propTypes = {
  firstname: PropTypes.string.isRequired,
  lastname: PropTypes.string.isRequired,
};

// Using legacy APIs

class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.firstname} {this.props.lastname}</div>;
  }
}
Hello.propTypes = {
  firstname: PropTypes.string.isRequired,
  lastname: PropTypes.string.isRequired,
};
```

### Activity

- [ ] Status Done / Not

### More info

**Documentation**

- React Documentation - [static propTypes](https://react.dev/reference/react/Component#static-proptypes)
- Flow.js Documentation - [React](https://flow.org/en/docs/react/)

**Comment by AMISH-KHAN** [comment]
I will like to work on this!!

**Comment by AMISH-KHAN** [comment]
hey @Ajay-Dhangar is what I am supposed to do:

![image](https://github.com/CodeHarborHub/codeharborhub/assets/123164129/538746f7-479a-42d3-a938-87ffadcac161)

**Comment by Ajay-Dhangar** [comment]
send pr I will checkout

**Comment by Ajay-Dhangar** [comment]
> send pr I will checkout

because we can do but first we need make simple and easy for best not complex to others

**Comment by AMISH-KHAN** [comment]
@Ajay-Dhangar  please check pr #199
