### ISSUE TITLE
Add Contact Us Page

### ISSUE THREAD

**Issue by Hemashree21** [CodeHarborHub/codeharborhub#193]
The footer link Contact Us is not working, hence I want to work on this issue and design a contact us page.
@Ajay-Dhangar can you please assign this to me?

![image](https://github.com/CodeHarborHub/codeharborhub/assets/138188163/169706d8-6759-4ff0-a714-59dfe38d0e6b)

**Comment by harshcodesit** [comment]
I can add an immersive contact us page with a contact form , can also add map if required

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar can i work on this?

**Comment by Ajay-Dhangar** [comment]
> hi @Ajay-Dhangar can i work on this?

I already work on it for our site and on going so, not try it.
