### ISSUE TITLE
Feature Request: [[Brief Description of Feature]] moving the project to vite

### ISSUE THREAD

**Issue by AMISH-KHAN** [CodeHarborHub/codeharborhub#209]
the current project is taking a lot of time before starting.
we can move it to the vite which is a build tool that aims to provide a faster and leaner development experience for modern web projects.

a lot more here https://vitejs.dev/guide/

**Comment by Ajay-Dhangar** [comment]
I know but this project is full based on [Docusaurus](https://docusaurus.io/). So, read all about this
