### ISSUE TITLE
Feature Request: Adding Leetcode problems 1300 - 1399

### ISSUE THREAD

**Issue by Code-eat-sleep-include** [CodeHarborHub/codeharborhub#220]
* **Description:** Leetcode problems 1300 - 1399 are missing.
* **Use Case:** Will add it up.

**Comment by Code-eat-sleep-include** [comment]
@Ajay-Dhangar Kindly assign me this issue!

**Comment by Tirth-chokshi** [comment]
@Ajay-Dhangar I can complete this

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar I can complete this

already assigned so, work on other.

**Comment by Ajay-Dhangar** [comment]
@Code-eat-sleep-include complete your task today's only and #222 is reference for you, If you don't done then I will assign to @Tirth-chokshi, because @Tirth-chokshi is done this task.

**Comment by Code-eat-sleep-include** [comment]
@Ajay-Dhangar Sure, I'll complete it by tonight.
