### ISSUE TITLE
Feature Request: Leetcode Problems 1400-1499

### ISSUE THREAD

**Issue by Code-eat-sleep-include** [CodeHarborHub/codeharborhub#221]
* **Description:** Leetcode Problems 1400-1499 are missing.
* **Use Case:** Will add it up.

**Comment by Code-eat-sleep-include** [comment]
@Ajay-Dhangar I would like to work on this task, kindly assign me this issue!

**Comment by Tirth-chokshi** [comment]
Can you assign me this I can complete it @Ajay-Dhangar

**Comment by Code-eat-sleep-include** [comment]
@Ajay-Dhangar I'm almost done with the task. I'll complete it by today, kindly assign me Sir.

**Comment by Ajay-Dhangar** [comment]
@Code-eat-sleep-include okay, and complete this very soon.
