### ISSUE TITLE
Bug Report: Solution Links are not working in DSA problems page

### ISSUE THREAD

**Issue by kaali001** [CodeHarborHub/codeharborhub#285]
* **Description:**

All the  view solution link in front of  Leetcode problems are redirected to same page instead of going to the particular Leetcode problem solution page.

* **Steps to Reproduce:** 

- Go to this page - https://www.codeharborhub.live/dsa-problems/leetcode-problems/0000-0099
- And click on any solution links

* **Screenshots or Screencast:**

![image](https://github.com/CodeHarborHub/codeharborhub/assets/115466381/552c2a1a-e190-4f86-a3ae-cd058bb65eb3)

I would like to on this issue under GSsoc , assign it to me.

**Comment by Ajay-Dhangar** [comment]
> * **Description:**
> 
> All the view solution link in front of Leetcode problems are redirected to same page instead of going to the particular Leetcode problem solution page.
> 
> * **Steps to Reproduce:**
> 
> * Go to this page - https://www.codeharborhub.live/dsa-problems/leetcode-problems/0000-0099
> * And click on any solution links
> 
> * **Screenshots or Screencast:**
> 
> ![image](https://private-user-images.githubusercontent.com/115466381/334532359-552c2a1a-e190-4f86-a3ae-cd058bb65eb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDE5MTgsIm5iZiI6MTcxNjk0MTYxOCwicGF0aCI6Ii8xMTU0NjYzODEvMzM0NTMyMzU5LTU1MmMyYTFhLWUxOTAtNGY4Ni1hM2FlLWNkMDU4YmI2NWViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwMDEzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDM4NWM3N2VhNjhmNTc4OTYyMzAwNGE3Y2Y3YjNiYzAzMzFhYjM2Y2YxNTZkMmFlNGI4MjFhNjM5NDU5NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZDu2wfMPZU9YuVbBMi0kVIrQsIAsAsHjypMYyuuD0Qk)
> 
> I would like to on this issue under GSsoc , assign it to me.

I know we need solution on our page and we are working on it.

**Comment by Ajay-Dhangar** [comment]
We use `#` as a placeholder for empty links. We will replace it with our solution.
