### ISSUE TITLE
Add Solution 

### ISSUE THREAD

**Issue by AmrutaJayanti** [CodeHarborHub/codeharborhub#302]
In the before PR, I added solution to Add Two Numbers 0002. If its good, Please assign the task to add solution to next problem.

**Comment by Ajay-Dhangar** [comment]
Yah, sure but Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone.
