### ISSUE TITLE
[Feature Request]: About us Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [CodeHarborHub/codeharborhub#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create an about us page for the website so that user can get an abstract view of the website .

### Use Case

![Screenshot 2024-05-31 131124](https://github.com/CodeHarborHub/codeharborhub/assets/118350936/096b656f-e757-40b6-9c42-28ccb5fe805b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
already, available  https://www.codeharborhub.live/about/

**Comment by Ayushmaanagarwal1211** [comment]
Oh i didn't see it
