### ISSUE TITLE
Setting up your development environment

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#31]

**Comment by PrathicaShettyM** [comment]
@Ajay-Dhangar Sir can u please assign me this task under GSSoC'24?

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i'd love to work on this if it's still available

**Comment by iamanolive** [comment]
@Ajay-Dhangar submitted a PR for this issue. please review.
