### ISSUE TITLE
[Geeks for Geeks Solution]: Value Equal to Index Value

### ISSUE THREAD

**Issue by iamanolive** [CodeHarborHub/codeharborhub#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Since there is an issue created for adding all problems from the Geeks for Geeks website, I'd like to add in the solutions. Would like to work on the "Value equal to index value" problem to begin with (link: https://www.geeksforgeeks.org/problems/value-equal-to-index-value1330/)

### Use Case

Provide users with easy access to solutions.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by iamanolive** [comment]
@Ajay-Dhangar can i work on this?

**Comment by Ajay-Dhangar** [comment]
Sure, you can work on it.

**Comment by iamanolive** [comment]
@Ajay-Dhangar submitted PR.
