### ISSUE TITLE
[Feature Request]: Adding Sections in Javascript

### ISSUE THREAD

**Issue by Yashgabani845** [CodeHarborHub/codeharborhub#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i don't want to make multiple level 2 PRs and issues for 1 or 2 sections 
i woll cover following sections of javascript

1. Js object Constrctuor
2. js array methods
3. js loops
4. js conditional satements and operator
all of these topics are important and od medium or hard category
i will make sure these topics would be easy to understand by my documentation
i will add notes,importatnt highlights and images
to make it simple

### Use Case

1. learning js
2. javascript topics description

### Benefits

i will add multiple topics with quality documentation

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar please assign me this issue

**Comment by Ajay-Dhangar** [comment]
Sure, I'll assign you level 3 in PR based on the quality of your content. If you produce high-quality work, you'll receive the level 3.
