### ISSUE TITLE
HTML elements and tags

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#36]

**Comment by SkandSingh** [comment]
Hello, I would like to contribute under GSSpc'24. Please assign me this task.

**Comment by Ajay-Dhangar** [comment]
## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Docusaurus Documentation](https://docusaurus.io/docs/docs-introduction)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Comment by Ajay-Dhangar** [comment]
And For our page code like: https://github.com/CodeHarborHub/codeharborhub/blob/main/docs/html/intro-html.md?plain=1
