### ISSUE TITLE
HTML syntax and structure

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#37]

**Comment by SkandSingh** [comment]
Hello, Please assign me this issue. I would love to work on this!!

**Comment by Ajay-Dhangar** [comment]
## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Comment by SkandSingh** [comment]
Thanks, I will start working on this
