### ISSUE TITLE
[Leetcode]: Generate parentheses

### ISSUE THREAD

**Issue by manishh12** [CodeHarborHub/codeharborhub#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 22.Generate parentheses.

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. You can also refer to the [live preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum) for more details.

If you create the content according to this structure, I will assign it a level3 rating. However, if you cannot meet this requirement, I will need to update the content based on my specifications and assign you level2.
