### ISSUE TITLE
Bug Report: [Homepage image overlaps to the card]

### ISSUE THREAD

**Issue by Abhiiii-001** [CodeHarborHub/codeharborhub#38]
On the homepage the coding image overlap on cards which looks awkward...
I can fix it ..plz assign to me this task.

Thank you;)
![Screenshot 2024-05-11 094633](https://github.com/CodeHarborHub/codeharborhub/assets/114284738/090af983-29a2-40e9-b03e-04aaf7832bb5)
![Screenshot 2024-05-11 094633](https://github.com/CodeHarborHub/codeharborhub/assets/114284738/a781cb91-0f51-4f2b-a760-1a7e6fb30919)

**Comment by Ajay-Dhangar** [comment]
Can you Shared width and height of this view port (Because in my side all is okay) So, I need size of your browser

**Comment by Abhiiii-001** [comment]
It is 1920px * 919px
________________________________

**Comment by Ajay-Dhangar** [comment]
Thanks, I will check it
