### ISSUE TITLE
Feature Request: [Cards UI Improvement]

### ISSUE THREAD

**Issue by Abhiiii-001** [CodeHarborHub/codeharborhub#39]
As you see the image below that some cards are mismatch and not looking so good.
I can improve it so plz assign this task to me .

Thank You:)
![Screenshot 2024-05-11 095425](https://github.com/CodeHarborHub/codeharborhub/assets/114284738/ad07fd64-49b5-4f54-b8ea-15c8ae1bfdee)

**Comment by Chanc2206** [comment]
can you assign this project to me?
