### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#46]
- [ ] #43 
- [ ] #44 
- [ ] #45

**Comment by AryanAg08** [comment]
Hii i want to work on this under GSSoC 24

**Comment by AryanAg08** [comment]
Thanks!! I will start working on it.

**Comment by Ajay-Dhangar** [comment]
## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Comment by AryanAg08** [comment]
Done With the work please accept my pull request!!
