### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#49]

**Comment by Tirth-chokshi** [comment]
Hi, Please assign me this issue. I would love to work on this!! under GSSOC'24

**Comment by Ajay-Dhangar** [comment]
first pull main branch and add your code in our template file which is assigned you.

**Comment by Tirth-chokshi** [comment]
I will proceed with these steps, thanks for assist!! already started working on this
