### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub#52]

**Comment by KDHarsh24** [comment]
Can I do this?
I could Add some GSAP controls to it and give it a modern design if in specific part u need design u can specify

**Comment by Ajay-Dhangar** [comment]
Sure, and

**Resources for Guidance**

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- https://www.codeharborhub.live/community/features
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Comment by KDHarsh24** [comment]
Can U just tell me in which part these are needed as I will not be doing it in hero part much as it is already in a simple good shape

**Comment by Ajay-Dhangar** [comment]
https://github.com/CodeHarborHub/codeharborhub/tree/main/docs/html/responsive-web-design

**Comment by KDHarsh24** [comment]
Sorry, 
For the late response I was busy in other scheduled works
I will be contributing regularly from now

**Comment by Tirth-chokshi** [comment]
Hey @Ajay-Dhangar i have completed this issue please check the pull request #144
